.PHONY: clean All

All:
	@echo "----------Building project:[ Assignment3 - Debug ]----------"
	@cd "Assignment3" && $(MAKE) -f  "Assignment3.mk"
clean:
	@echo "----------Cleaning project:[ Assignment3 - Debug ]----------"
	@cd "Assignment3" && $(MAKE) -f  "Assignment3.mk" clean
